# Generated by Django 4.2.28 on 2026-03-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='complaint_files/'),
        ),
    ]
