# Generated by Django 4.2.28 on 2026-03-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='pdf_sent',
            field=models.BooleanField(default=False),
        ),
    ]
