# Generated by Django 4.2.28 on 2026-03-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_pdf_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='pdf_sent',
        ),
    ]
